### PR TITLE
allow --output-file to be '-' for stdout

### PR DESCRIPTION
**Pull request by hayguen**
all other program outputs now go to stderr - for not polluting stdout

### CODE REVIEW

**Comment by hayguen** [comment]
it was possible to use '-' for --output-file before .. but the RIFF WAVE header was still in the output, which made the pipe output unusable

**Comment by Anthony96922** [comment]
I don't recommend using stdout. Try using a FIFO pipe instead.

**Comment by hayguen** [comment]
why not? looks to run fine here with my changes ..
however, if you don't accept this patch,
then consider documenting, that stdout will not work as output

**Comment by Anthony96922** [comment]
I've updated mpx_gen.c so there is no header. You'll need to rebase your patch. Your other changes should be good.

**Comment by hayguen** [comment]
did the rebase. the output via
"./mpxgen -a stereo_44100.wav -o -  >mpx.bin"
looks good for me

**Pull request merged**
